// KerboScript mission profile.
SET MISSION_ID TO "kerbin_survey".
SET MISSION_NAME TO "FDR1 Kerbin Survey".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO "".
SET SEQUENCE TO "ARM,FLY,DONE".
SET DRONE_STYLE TO "TILT".
SET DRONE_CRUISE_AGL TO 60.
SET DRONE_CRUISE_SPEED TO 25.
