// KerboScript mission profile.
SET MISSION_ID TO "minmus_hops".
SET MISSION_NAME TO "FDR1 Minmus Biome Hops".
SET TARGET_ TO "MINMUS".
SET PAYLOADS TO LIST().
SET SEQUENCE TO LIST("ARM", "FLY", "DONE").
SET DRONE_STYLE TO "RCS".
SET DRONE_CRUISE_AGL TO 35.
SET DRONE_CRUISE_SPEED TO 12.
SET DRONE_RCS_ACC TO 1.2.
SET DRONE_VS_CAP TO 4.
