// KerboScript mission profile.
SET MISSION_ID TO "mun_hops".
SET MISSION_NAME TO "FDR1 Vacuum Hops".
SET TARGET_ TO "MUN".
SET PAYLOADS TO LIST().
SET SEQUENCE TO LIST("ARM", "FLY", "DONE").
SET DRONE_STYLE TO "RCS".
SET DRONE_CRUISE_AGL TO 40.
SET DRONE_CRUISE_SPEED TO 15.
SET DRONE_RCS_ACC TO 1.5.
SET DRONE_VS_CAP TO 5.
