// KerboScript mission profile.
SET MISSION_ID TO "duna_ike_flyby_probe".
SET MISSION_NAME TO "Duna/Ike Flyby Probe".
SET TARGET_ TO "DUNA".
SET PAYLOADS TO "PROBE".
SET SEQUENCE TO "LAUNCH,FAIR,ANTS,PARK,XING,BPLANE,COAST_1HALF,REFINE_BPLANE,COAST_2HALF,FLYBY,DONE".
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET CAPTURE_PE TO 85000.
SET FLYBY_POST_PE_HOLD TO 7200.
SET FLYBY_EXIT_SOI TO 0.
SET KEEP_WARP TO 1.
