// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "duna_ike_flyby_probe",
    "MISSION_NAME", "Duna/Ike Flyby Probe",
    "TARGET", "DUNA",
    "PAYLOADS", "PROBE",
    "SEQUENCE", "LAUNCH,FAIR,ANTS,PARK,XING,BPLANE,COAST_1HALF,REFINE_BPLANE,COAST_2HALF,FLYBY,DONE",
    "PARKING_ALT", 85000,
    "LAUNCH_INCLINATION", 0,
    "CAPTURE_PE", 85000,
    "FLYBY_POST_PE_HOLD", 7200,
    "FLYBY_EXIT_SOI", 0,
    "KEEP_WARP", 1
).
