// KerboScript mission profile.
SET MISSION_ID TO "jool_flyby_probe".
SET MISSION_NAME TO "Jool Flyby Probe".
SET TARGET_ TO "JOOL".
SET PAYLOADS TO "PROBE".
SET SEQUENCE TO "LAUNCH,FAIR,ANTS,PARK,XING,BPLANE,COAST_1HALF,REFINE_BPLANE,COAST_2HALF,FLYBY,DONE".
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET CAPTURE_PE TO 250000.
SET FLYBY_POST_PE_HOLD TO 14400.
SET FLYBY_EXIT_SOI TO 0.
SET KEEP_WARP TO 1.
