// KerboScript mission profile.
SET MISSION_ID TO "kerbin_telescope_discovery".
SET MISSION_NAME TO "Kerbin TB-75M Telescope Discovery".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("SCISAT").
SET SEQUENCE TO LIST("LAUNCH", "FAIR", "ANTS", "PARK", "RAISE", "CIRC", "INCLINE", "RELAY_OPS", "DONE").
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET TARGET_PE TO 600000.
SET TARGET_AP TO 600000.
SET TARGET_INCLINATION TO 0.
