// KerboScript mission profile.
SET MISSION_ID TO "minmus_science_orbiter".
SET MISSION_NAME TO "Minmus Science Orbiter".
SET TARGET_ TO "MINMUS".
SET PAYLOADS TO "SCISAT".
SET SEQUENCE TO "PRELAUNCH,LAUNCH,FAIR,ANTS,PARK,XING,BPLANE,COAST_1HALF,REFINE_BPLANE,COAST_2HALF,CAPTURE,SHAPE,RELAY_OPS,DONE".
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET CAPTURE_PE TO 15000.
SET CAPTURE_INC TO 90.
SET CAPTURE_DIR TO "POLAR".
SET TARGET_PE TO 30000.
SET TARGET_AP TO 30000.
SET SHAPE_PE TO 30000.
SET SHAPE_AP TO 30000.
SET SHAPE_INC TO 90.
SET KEEP_WARP TO 1.
