// KerboScript mission profile.
SET MISSION_ID TO "mun_rover".
SET MISSION_NAME TO "FR3C Mun Rover Lander".
SET TARGET_ TO "MUN".
SET PAYLOADS TO LIST("ASSISTROVER").
SET SEQUENCE TO LIST("LAUNCH", "FAIR", "ANTS", "PARK", "XING", "BPLANE", "COAST_1HALF", "REFINE_BPLANE", "COAST_2HALF", "CAPTURE", "SHAPE", "LAND_DEORBIT", "LAND_ASSIST", "LAND", "ROVER", "DONE").
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET CAPTURE_PE TO 15000.
SET CAPTURE_INC TO 90.
SET CAPTURE_DIR TO "POLAR".
SET TARGET_PE TO 20000.
SET TARGET_AP TO 20000.
SET SHAPE_PE TO 20000.
SET SHAPE_AP TO 20000.
SET SHAPE_INC TO 90.
SET TARGET_TOLERANCE TO 2500.
SET GUIDANCE_ALT TO 5000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 5.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 512.
SET LANDING_SITE_SCAN_ENABLE TO 1.
SET LANDING_SITE_SCAN_RADIUS TO 1500.
SET LANDING_SITE_SCAN_STEP TO 250.
SET LANDING_SITE_MAX_SLOPE TO 12.
SET MAX_TILT TO 15.
SET RELOAD_AFTER_LAND_ASSIST TO 1.
SET RELOAD_AFTER_LAND TO 1.
