// KerboScript mission profile.
SET MISSION_ID TO "eve_scisat_entry".
SET MISSION_NAME TO "Falcon Eve SCISat Entry".
SET TARGET_ TO "EVE".
SET PAYLOADS TO "SCISAT".
SET SEQUENCE TO "PRELAUNCH,LAUNCH,FAIR,ANTS,PARK,XING,BPLANE,COAST_1HALF,REFINE_BPLANE,COAST_2HALF,AEROBRAKE,DONE".

// Kerbin launch and Eve transfer.
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET LAUNCH_PLANE_MODE TO "INTERPLANETARY".
SET TRANSFER_SCAN_SAMPLES_PER_ORBIT TO 16.
SET COAST_AUTO_WARP TO 1.
SET COAST_HIBERNATE TO 1.
SET KEEP_WARP TO 1.

// Eve atmosphere starts near 90km. This profile intentionally only
// enters the atmosphere and holds the configured entry attitude; it does
// not attempt descent recovery or return.
SET CAPTURE_PE TO 75000.
SET CAPTURE_INC TO 0.
SET CAPTURE_DIR TO "PROGRADE".
SET AEROBRAKE_REENTRY_DIR TO "RETROGRADE".
SET AEROBRAKE_ARM_CHUTES TO 0.
