// KerboScript mission profile.
SET MISSION_ID TO "falcon_lko_target".
SET MISSION_NAME TO "Falcon LKO Target".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("UNMANNED").
SET SEQUENCE TO LIST("LAUNCH", "ANTS", "PARK", "DONE").
SET PARKING_ALT TO 74000.
SET LAUNCH_INCLINATION TO 28.
SET LIBS_EXTRA TO LIST("solar").
