// KerboScript mission profile.
SET MISSION_ID TO "launch_to_rendezvous".
SET MISSION_NAME TO "Launch to Rendezvous".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("CREW").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "ANTS", "PARK", "RDV", "MATCH", "DONE").
SET PARKING_ALT TO 75000.
SET RENDEZVOUS_TARGET TO "Eilory's Wreckage".
SET LAUNCH_RDV_ASCENT_TIME TO 300.
SET LAUNCH_RDV_LEAD TO 70.
SET LAUNCH_RDV_MAX_WINDOWS TO 16.
SET MATCH_FINAL_DIST TO 150.
SET LIBS_EXTRA TO LIST("launch@PARK", "solar").
SET TARGET_LAT TO -0.1.
SET TARGET_LNG TO -74.25.
SET TARGET_TOLERANCE TO 1000.
SET REENTRY_PE TO 30000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 8.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 128.
SET TARGET_DEORBIT_MIN_LEAD TO 300.
SET DESCENT_DECOUPLE_ALT TO 34000.
SET DESCENT_CHUTES_TAG TO "descent_chutes".
SET DESCENT_RELEASE_ALT TO 38000.
SET DESCENT_HEAT_SHIELD_DROP_ALT TO -1.
SET DESCENT_BAY_REOPEN_ALT TO 42000.
SET DESCENT_SERVICE_ARM_ALT TO 60000.
SET DESCENT_SERVICE_SEPARATION_DROP TO 0.15.
SET DESCENT_SERVICE_RELEASE_ALT TO 500.
