// KerboScript mission profile.
SET MISSION_ID TO "minmus_scansat_polar".
SET MISSION_NAME TO "Minmus SCANsat Polar Mapper".
SET TARGET_ TO "MINMUS".
SET PAYLOADS TO LIST("SCANSAT").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "FAIR", "ANTS", "PARK", "XING", "BPLANE", "COAST_1HALF", "REFINE_BPLANE", "COAST_2HALF", "CAPTURE", "SHAPE", "SCANSAT_OPS", "DONE").
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET CAPTURE_PE TO 15000.
SET CAPTURE_INC TO 90.
SET CAPTURE_DIR TO "POLAR".
SET SHAPE_PE TO 249000.
SET SHAPE_AP TO 249000.
SET SHAPE_INC TO 90.
SET SCANSAT_DECOUPLER_TAG TO "scansat_decoupler".
SET SCANSAT_DISPOSE_CARRIER TO 0.
SET SCANSAT_AUTO_DEORBIT TO 1.
SET SCANSAT_TARGET_COVERAGE TO 99.1.
SET SCANSAT_REQUIRED_TYPES TO LIST("LOW_RES_ALTIMETRY", "LOW_RES_RESOURCES", "BIOME").
SET SCANSAT_DEORBIT_PE TO 0.
SET SCANSAT_DEORBIT_MAX_TIME TO 600.
SET SCANSAT_POWER_LOW TO 0.3.
SET SCANSAT_POWER_RESUME TO 0.6.
SET SOLAR_REORIENT_PERIOD TO 21600.
