// KerboScript mission profile.
SET MISSION_ID TO "duna_scansat_polar".
SET MISSION_NAME TO "FalconHeavy Duna SCANsat Polar Mapper".
SET TARGET_ TO "DUNA".
SET PAYLOADS TO LIST("SCANSAT").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "FAIR", "ANTS", "PARK", "XING", "BPLANE", "COAST_1HALF", "REFINE_BPLANE", "COAST_2HALF", "CAPTURE", "SHAPE", "SCANSAT_OPS", "DONE").

// Kerbin launch and Duna transfer.
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET LAUNCH_PLANE_MODE TO "INTERPLANETARY".
SET TRANSFER_SCAN_SAMPLES_PER_ORBIT TO 16.
SET COAST_AUTO_WARP TO 1.
SET COAST_HIBERNATE TO 1.
SET KEEP_WARP TO 1.

// Duna polar mapping orbit. Arrive with a 50km Pe, then shape up
// to the final 300km polar mapping orbit.
SET CAPTURE_PE TO 50000.
SET CAPTURE_INC TO 90.
SET CAPTURE_DIR TO "POLAR".
SET TARGET_PE TO 300000.
SET TARGET_AP TO 300000.
SET SHAPE_PE TO 300000.
SET SHAPE_AP TO 300000.
SET SHAPE_INC TO 90.
SET SHAPE_ALT_TOL TO 5000.

// SCANsat deployment and mapping.
SET SCANSAT_DECOUPLER_TAG TO "scansat_decoupler".
SET SCANSAT_DISPOSE_CARRIER TO 0.
SET SCANSAT_AUTO_DEORBIT TO 0.
SET SCANSAT_POWER_GUARD TO 1.
SET SCANSAT_TARGET_COVERAGE TO 99.1.
SET SCANSAT_REQUIRED_TYPES TO LIST("LOW_RES_ALTIMETRY", "LOW_RES_RESOURCES", "BIOME").
SET SCANSAT_POWER_LOW TO 0.3.
SET SCANSAT_POWER_RESUME TO 0.6.
SET SOLAR_REORIENT_PERIOD TO 43200.
