// KerboScript mission profile.
SET MISSION_ID TO "duna_ike_scisat_lander".
SET MISSION_NAME TO "FalconHeavy Duna/Ike SCISat Lander".
SET TARGET_ TO "DUNA".
SET PAYLOADS TO LIST("SCISAT").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "FAIR", "ANTS", "PARK", "XING", "BPLANE", "COAST_1HALF", "REFINE_BPLANE", "COAST_2HALF", "DUNA_AEROCAPTURE", "SHAPE", "IKE_SETUP").

// Kerbin launch and Duna transfer.
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET LAUNCH_PLANE_MODE TO "INTERPLANETARY".
SET TRANSFER_SCAN_SAMPLES_PER_ORBIT TO 16.
SET COAST_AUTO_WARP TO 1.
SET COAST_HIBERNATE TO 1.
SET KEEP_WARP TO 1.

// Aggressive Duna aerocapture. The current direct-entry lander uses
// ~18km Pe; 20km should provide useful braking while leaving a small
// corridor for simulation tuning.
SET CAPTURE_PE TO 20000.
SET CAPTURE_INC TO 0.
SET CAPTURE_DIR TO "PROGRADE".
SET DUNA_AEROCAPTURE_PE TO 20000.
SET DUNA_AEROCAPTURE_MIN_PE TO 17000.
SET DUNA_AEROCAPTURE_MAX_PE TO 25000.
SET DUNA_AEROCAPTURE_TARGET_AP TO 5000000.
SET DUNA_AEROCAPTURE_MAX_RETRO_DV TO 125.
SET DUNA_SAFE_PE TO 85000.

// Safe post-aerocapture Duna orbit, shaped for a cheap Ike flyby setup.
SET SHAPE_PE TO 85000.
SET SHAPE_AP TO 2880000.
SET SHAPE_INC TO 0.2.
SET SHAPE_ALT_TOL TO 10000.

// Ike flyby leg configured by IKE_SETUP.
SET IKE_FLYBY_PE TO 25000.
SET IKE_FLYBY_INC TO -1.
SET IKE_FLYBY_POST_PE_HOLD TO 600.
SET IKE_FLYBY_EXIT_SOI TO 0.
SET IKE_TRANSFER_SCAN_LOOKAHEAD_HOURS TO 24.
SET IKE_TRANSFER_SCAN_SAMPLES_PER_ORBIT TO 32.
SET IKE_BPLANE_DV_CAP TO 40.
SET IKE_REFINE_BPLANE_DV_CAP TO 5.
SET IKE_REFINE_BPLANE_MAX_BURNS TO 8.

// Final Duna atmospheric entry configured by DUNA_ENTRY_SETUP.
SET DUNA_ENTRY_PE TO 18000.
SET DUNA_ENTRY_PE_TOL TO 5000.
SET DUNA_ENTRY_LOWER_PE_MAX_DV TO 150.
SET AEROBRAKE_TARGETING TO 0.
SET AEROBRAKE_REENTRY_DIR TO "RETROGRADE".
SET AEROBRAKE_ARM_CHUTES TO 1.

// Atmospheric descent / soft landing.
SET DESCENT_CHUTES_TAG TO "descent_chutes".
SET DESCENT_RELEASE_ALT TO 12000.
SET DESCENT_DROGUE_CUT_ALT TO 3500.
SET DESCENT_FAIRING_TAG TO "descent_fairing".
SET DESCENT_FAIRING_DEPLOY_SPEED TO 60.
SET DESCENT_DECOUPLER_TAG TO "descent_decoupler".
SET DESCENT_DECOUPLE_ALT TO 8000.
SET DESCENT_HEAT_SHIELD_DROP_ALT TO -1.
SET DESCENT_BAY_REOPEN_ALT TO 6000.
SET DESCENT_ENGINE_ASSIST TO 1.
SET DESCENT_ENGINE_ASSIST_ALT TO 1200.
SET DESCENT_ENGINE_ASSIST_TOUCHDOWN_VS TO 2.5.
SET DESCENT_ENGINE_ASSIST_HIGH_VS TO 12.
SET DESCENT_ENGINE_ASSIST_MAX_THROTTLE TO 0.85.
