// KerboScript mission profile.
SET MISSION_ID TO "duna_scisat_lander".
SET MISSION_NAME TO "Falcon Duna SCISat Lander".
SET TARGET_ TO "DUNA".
SET PAYLOADS TO LIST("SCISAT").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "FAIR", "ANTS", "PARK", "XING", "BPLANE", "COAST_1HALF", "REFINE_BPLANE", "COAST_2HALF", "AEROBRAKE", "DESCENT", "DONE").

// Kerbin launch and Duna transfer.
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET LAUNCH_PLANE_MODE TO "INTERPLANETARY".
SET TRANSFER_SCAN_SAMPLES_PER_ORBIT TO 16.
SET KEEP_WARP TO 1.

// Direct Duna atmospheric arrival. Duna atmosphere ends near 50km;
// this first-flight profile aims well inside it so DESCENT can commit
// to landing instead of aerobraking into a skip-out orbit.
SET CAPTURE_PE TO 18000.
SET CAPTURE_INC TO 0.
SET CAPTURE_DIR TO "PROGRADE".
SET AEROBRAKE_REENTRY_DIR TO "RETROGRADE".
SET AEROBRAKE_ARM_CHUTES TO 1.

// Atmospheric descent / soft landing.
SET DESCENT_CHUTES_TAG TO "descent_chutes".
SET DESCENT_RELEASE_ALT TO 12000.
SET DESCENT_DROGUE_CUT_ALT TO 3500.
SET DESCENT_FAIRING_TAG TO "descent_fairing".
SET DESCENT_FAIRING_DEPLOY_SPEED TO 60.
SET DESCENT_DECOUPLER_TAG TO "descent_decoupler".
SET DESCENT_DECOUPLE_ALT TO 8000.
SET DESCENT_HEAT_SHIELD_DROP_ALT TO -1.
SET DESCENT_BAY_REOPEN_ALT TO 6000.
SET DESCENT_ENGINE_ASSIST TO 1.
SET DESCENT_ENGINE_ASSIST_ALT TO 1200.
SET DESCENT_ENGINE_ASSIST_TOUCHDOWN_VS TO 2.5.
SET DESCENT_ENGINE_ASSIST_HIGH_VS TO 12.
SET DESCENT_ENGINE_ASSIST_MAX_THROTTLE TO 0.85.

SET_PRELAUNCH_TRANSFER_DEPARTURE_IN 0.
SET COAST_AUTO_WARP TO 0.
