// KerboScript mission profile.
SET MISSION_ID TO "minmus_science_return_2".
SET MISSION_NAME TO "Minmus Science Return 2".
SET TARGET_ TO "MINMUS".
bootLibLoad("configs/landing-minmus").
SET PAYLOADS TO LIST("SCISAT").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "FAIR", "ANTS", "PARK", "XING", "BPLANE", "COAST_1HALF", "REFINE_BPLANE", "COAST_2HALF", "CAPTURE", "SHAPE", "LAND_DEORBIT", "LAND_ASSIST", "SURFACE_RETURN_SETUP").

// Kerbin launch and Minmus transfer.
SET PARKING_ALT TO 80000.
SET LAUNCH_INCLINATION TO 0.
SET LAUNCH_PLANE_MODE TO "BODY_ORBIT".
SET TRANSFER_SCAN_SAMPLES_PER_ORBIT TO 16.
SET EXTEND_ALT TO 72000.
SET FAIRING_ALT TO 71500.

// Minmus capture and post-capture polar parking orbit.
SET CAPTURE_PE TO 10000.
SET CAPTURE_INC TO 90.
SET CAPTURE_DIR TO "POLAR".
SET TARGET_PE TO 20000.
SET TARGET_AP TO 20000.
SET SHAPE_PE TO 20000.
SET SHAPE_AP TO 20000.
SET SHAPE_INC TO 90.
SET SHAPE_ALT_TOL TO 2500.

// Automated landing: contract site, with terrain refinement nearby.
// Replace TARGET_LAT/LNG with the contract coordinates before launch.
SET TARGET_LAT TO 0.
SET TARGET_LNG TO 0.
SET TARGET_LOCK TO 1.
SET LANDING_AUTO_TARGET TO 0.
SET LANDING_CONFIRM_TARGET TO 0.
SET TARGET_TOLERANCE TO 1500.
SET GUIDANCE_ALT TO 3000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 8.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 512.
SET TARGET_DEORBIT_MIN_LEAD TO 120.
SET LANDING_SITE_SCAN_ENABLE TO 1.
SET LANDING_SITE_SCAN_RADIUS TO 500.
SET LANDING_SITE_SCAN_STEP TO 100.
SET LANDING_SITE_MAX_SLOPE TO 8.
SET TERRAIN_CHECK_RADIUS TO 500.
SET TERRAIN_CHECK_STEP TO 100.
SET MAX_TILT TO 12.
SET RELOAD_AFTER_LAND_ASSIST TO 0.
SET RELOAD_AFTER_LAND TO 0.

// Surface relaunch and Kerbin return.
SET SURFACE_RETURN_PARKING_ALT TO 20000.
SET SURFACE_RETURN_INCLINATION TO 90.
SET RETURN_SEQUENCE TO LIST("ESCAPE", "COAST", "MCC", "AEROBRAKE", "DESCENT", "DONE").
SET RETURN_PE TO 35000.
SET RETURN_REENTRY_DIR TO "RETROGRADE".
SET RETURN_KSC_TARGET TO 0.
SET RETURN_ARM_CHUTES TO 1.
