// KerboScript mission profile.
SET MISSION_ID TO "kerbin_aop_lan_sample".
SET MISSION_NAME TO "Kerbin AoP/LAN Payload Sample".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("SCISAT").
SET SEQUENCE TO LIST("PRELAUNCH", "LAUNCH", "FAIR", "ANTS", "PARK", "RAISE", "CIRC", "INCLINE", "ELLIPTICAL", "RELAY_OPS", "DONE").
SET PARKING_ALT TO 73500.
SET LAUNCH_INCLINATION TO 37.
SET PRELAUNCH_PLANE_LEAD TO 145.
SET TARGET_PE TO 180000.
SET TARGET_AP TO 950000.
SET TARGET_INCLINATION TO 37.
SET CAPTURE_INC TO 37.
SET CAPTURE_LAN TO 256.0.
SET CAPTURE_AOP TO 153.6.
SET INCL_TOLERANCE TO 0.05.
SET MAX_INCL_CHANGE_DV TO 250.
SET ELLIPTICAL_MAX_NODE_DV TO 350.
