// KerboScript mission profile.
SET MISSION_ID TO "kerbin_sunsync".
SET MISSION_NAME TO "Kerbin Sun-Sync Satellite".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO "SCISAT".
SET SEQUENCE TO "LAUNCH,FAIR,ANTS,PARK,RAISE,CIRC,INCLINE,RELAY_OPS,DONE".
SET PARKING_ALT TO 73500.
SET LAUNCH_INCLINATION TO 98.
SET TARGET_PE TO 700000.
SET TARGET_AP TO 700000.
SET TARGET_INCLINATION TO 98.
