// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "krbcap1_lko",
    "MISSION_NAME", "KRBCAP1 LKO Orbit",
    "TARGET", "KERBIN",
    "PAYLOADS", "KRBCAP1",
    "SEQUENCE", "LAUNCH,ANTS,PARK,KSC_DEORBIT,DESCENT,DONE",
    "PARKING_ALT", 74000,
    "LAUNCH_INCLINATION", 30,
    "LIBS_EXTRA", "descent",
    "ORBIT_STAY_TIME", 10800,
    "LANDING_TARGET_LAT", -0.1,
    "LANDING_TARGET_LNG", -74.25,
    "LANDING_TARGET_TOLERANCE", 15000,
    "REENTRY_PE", 30000,
    "TARGET_DEORBIT_SCAN_ORBITS", 6,
    "TARGET_DEORBIT_SCAN_SAMPLES", 128,
    "TARGET_DEORBIT_COARSE_STOP_DIST", 15000,
    "TARGET_DEORBIT_SKIP_REFINE", 1,
    "TARGET_DEORBIT_PROCEED_ON_MISS", 1,
    "TARGET_DEORBIT_MIN_LEAD", 300,
    "DESCENT_RELEASE_ALT", 38000
).
