// KerboScript mission profile.
SET MISSION_ID TO "krbcap1_suborbital".
SET MISSION_NAME TO "KRBCAP1 Suborbital Hop".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO "KRBCAP1".
SET SEQUENCE TO "LAUNCH,SUBORBIT,DESCENT,DONE".
SET PARKING_ALT TO 72000.
SET LAUNCH_INCLINATION TO 0.
SET LIBS_EXTRA TO "suborbit@SUBORBIT, descent".
