// KerboScript mission profile.
SET MISSION_ID TO "mun_sat_delivery_2".
SET MISSION_NAME TO "Mun Satellite Delivery Contract 2".
SET TARGET_ TO "MUN".
SET PAYLOADS TO "SCISAT".
SET SEQUENCE TO "LAUNCH,FAIR,ANTS,PARK,XING,MCC,COAST,CAPTURE,CIRC,INCLINE,RELAY_OPS,DONE".
SET PARKING_ALT TO 80000.
SET LAUNCH_INCLINATION TO 0.
SET CAPTURE_PE TO 15000.
SET CAPTURE_INC TO 180.
SET CAPTURE_DIR TO "RETROGRADE".
SET CAPTURE_AOP TO 88.7.
SET TRANSFER_AOP_ERR_TOL TO 30.
SET TRANSFER_AOP_SCAN_TOL TO 20.
SET TARGET_PE TO 637497.
SET TARGET_AP TO 637497.
SET TARGET_INCLINATION TO 180.
