// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "mun_sat_delivery_2",
    "MISSION_NAME", "Mun Satellite Delivery Contract 2",
    "TARGET", "MUN",
    "PAYLOADS", "SCISAT",
    "SEQUENCE", "LAUNCH,FAIR,ANTS,PARK,XING,MCC,COAST,CAPTURE,CIRC,INCLINE,RELAY_OPS,DONE",
    "PARKING_ALT", 80000,
    "LAUNCH_INCLINATION", 0,
    "CAPTURE_PE", 15000,
    "CAPTURE_INC", 180,
    "CAPTURE_DIR", "RETROGRADE",
    "CAPTURE_AOP", 88.7,
    "TRANSFER_AOP_ERR_TOL", 30,
    "TRANSFER_AOP_SCAN_TOL", 20,
    "TARGET_PE", 637497,
    "TARGET_AP", 637497,
    "TARGET_INCLINATION", 180
).
