// KerboScript mission profile.
SET MISSION_ID TO "point_landing".
SET MISSION_NAME TO "Point Landing Delivery".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("KRBCAP1").
SET SEQUENCE TO LIST("LAUNCH", "ANTS", "PARK", "KSC_DEORBIT", "DESCENT", "DONE").
SET PARKING_ALT TO 73500.
SET LAUNCH_INCLINATION TO 0.
SET LIBS_EXTRA TO LIST("descent").
SET TARGET_LAT TO -0.1.
SET TARGET_LNG TO -74.25.
SET TARGET_TOLERANCE TO 15000.
SET REENTRY_PE TO 30000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 4.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 128.
SET TARGET_DEORBIT_MIN_LEAD TO 90.
SET DESCENT_DECOUPLER_TAG TO "descent_decoupler".
SET DESCENT_DECOUPLE_ALT TO 45000.
