// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "point_landing",
    "MISSION_NAME", "Point Landing Delivery",
    "TARGET", "KERBIN",
    "PAYLOADS", "KRBCAP1",
    "SEQUENCE", "LAUNCH,ANTS,PARK,KSC_DEORBIT,DESCENT,DONE",
    "PARKING_ALT", 73500,
    "LAUNCH_INCLINATION", 0,
    "LIBS_EXTRA", "descent",
    "TARGET_LAT", -0.1,
    "TARGET_LNG", -74.25,
    "TARGET_TOLERANCE", 15000,
    "REENTRY_PE", 30000,
    "TARGET_DEORBIT_SCAN_ORBITS", 4,
    "TARGET_DEORBIT_SCAN_SAMPLES", 128,
    "TARGET_DEORBIT_COARSE_STOP_DIST", 15000,
    "TARGET_DEORBIT_SKIP_REFINE", 1,
    "TARGET_DEORBIT_PROCEED_ON_MISS", 1,
    "TARGET_DEORBIT_MIN_LEAD", 90,
    "DESCENT_DECOUPLER_TAG", "descent_decoupler",
    "DESCENT_DECOUPLE_ALT", 45000
).
