// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "rescue_lko",
    "MISSION_NAME", "LKO Rescue",
    "TARGET", "KERBIN",
    "PAYLOADS", "KRBCAP1",
    "SEQUENCE", "PRELAUNCH,LAUNCH,ANTS,PARK,RDV,MATCH,CREW_XFER,KSC_DEORBIT,DESCENT,DONE",
    "PARKING_ALT", 73500,
    "LIBS_EXTRA", "launch@PARK, descent",
    "TARGET_LAT", -0.1,
    "TARGET_LNG", -74.25,
    "TARGET_TOLERANCE", 15000,
    "REENTRY_PE", 30000,
    "TARGET_DEORBIT_SCAN_ORBITS", 4,
    "TARGET_DEORBIT_SCAN_SAMPLES", 128,
    "TARGET_DEORBIT_MIN_LEAD", 90,
    "DESCENT_DECOUPLER_TAG", "descent_decoupler",
    "DESCENT_DECOUPLE_ALT", 45000
).
