GLOBAL FUNCTION dependencyBindPhase {
    PARAMETER phaseMap.
    PARAMETER phaseName.
    LOCAL phaseKey IS phaseName.
    IF phaseKey = "PREFLIGHT" { phaseMapSet(phaseMap, phaseKey, phasePreflight@). }
    ELSE IF phaseKey = "FLIGHT" { phaseMapSet(phaseMap, phaseKey, phaseFlight@). }
    ELSE IF phaseKey = "POST_FLIGHT" { phaseMapSet(phaseMap, phaseKey, phasePostFlight@). }
    ELSE IF phaseKey = "POSTFLIGHT" { phaseMapSet(phaseMap, phaseKey, phasePostflight@). }
    ELSE IF phaseKey = "EVA_SCIENCE" { phaseMapSet(phaseMap, phaseKey, phaseEvaScience@). }
    ELSE IF phaseKey = "SCIENCE_OPS" { phaseMapSet(phaseMap, phaseKey, phaseScienceOps@). }
    ELSE IF phaseKey = "SCIENCE_OPS_LOW" { phaseMapSet(phaseMap, phaseKey, phaseScienceOpsLow@). }
    ELSE IF phaseKey = "LAUNCH" { phaseMapSet(phaseMap, phaseKey, phaseLaunch@). }
    ELSE IF phaseKey = "FAIR" { phaseMapSet(phaseMap, phaseKey, phaseFair@). }
    ELSE IF phaseKey = "ANTS" { phaseMapSet(phaseMap, phaseKey, phaseAnts@). }
    ELSE IF phaseKey = "PARK" { phaseMapSet(phaseMap, phaseKey, phasePark@). }
    ELSE IF phaseKey = "ABORT" { phaseMapSet(phaseMap, phaseKey, phaseAbort@). }
    ELSE IF phaseKey = "PRELAUNCH" { phaseMapSet(phaseMap, phaseKey, phasePrelaunch@). }
    ELSE IF phaseKey = "SUBORBIT" { phaseMapSet(phaseMap, phaseKey, phaseSuborbit@). }
    ELSE IF phaseKey = "RDV" { phaseMapSet(phaseMap, phaseKey, phaseRdv@). }
    ELSE IF phaseKey = "MATCH" { phaseMapSet(phaseMap, phaseKey, phaseMatch@). }
    ELSE IF phaseKey = "CREW_XFER" { phaseMapSet(phaseMap, phaseKey, phaseCrewXfer@). }
    ELSE IF phaseKey = "XING" { phaseMapSet(phaseMap, phaseKey, phaseXing@). }
    ELSE IF phaseKey = "ESCAPE" { phaseMapSet(phaseMap, phaseKey, phaseEscape@). }
    ELSE IF phaseKey = "MCC" { phaseMapSet(phaseMap, phaseKey, phaseMcc@). }
    ELSE IF phaseKey = "AEROBRAKE" { phaseMapSet(phaseMap, phaseKey, phaseAerobrake@). }
    ELSE IF phaseKey = "DESCENT" { phaseMapSet(phaseMap, phaseKey, phaseDescent@). }
    ELSE IF phaseKey = "KSC_DEORBIT" { phaseMapSet(phaseMap, phaseKey, phaseKscDeorbit@). }
    ELSE IF phaseKey = "COAST" { phaseMapSet(phaseMap, phaseKey, phaseCoast@). }
    ELSE IF phaseKey = "COAST_1HALF" { phaseMapSet(phaseMap, phaseKey, phaseCoast1half@). }
    ELSE IF phaseKey = "COAST_2HALF" { phaseMapSet(phaseMap, phaseKey, phaseCoast2half@). }
    ELSE IF phaseKey = "CAPTURE" { phaseMapSet(phaseMap, phaseKey, phaseCapture@). }
    ELSE IF phaseKey = "FLYBY" { phaseMapSet(phaseMap, phaseKey, phaseFlyby@). }
    ELSE IF phaseKey = "CIRC" { phaseMapSet(phaseMap, phaseKey, phaseCirc@). }
    ELSE IF phaseKey = "RAISE" { phaseMapSet(phaseMap, phaseKey, phaseRaise@). }
    ELSE IF phaseKey = "INCLINE" { phaseMapSet(phaseMap, phaseKey, phaseIncline@). }
    ELSE IF phaseKey = "ELLIPTICAL" { phaseMapSet(phaseMap, phaseKey, phaseElliptical@). }
    ELSE IF phaseKey = "TARGETED_DEORBIT" { phaseMapSet(phaseMap, phaseKey, phaseTargetedDeorbit@). }
    ELSE IF phaseKey = "RELEASE_PROBE" { phaseMapSet(phaseMap, phaseKey, phaseReleaseProbe@). }
    ELSE IF phaseKey = "RELAY_OPS" { phaseMapSet(phaseMap, phaseKey, phaseRelayOps@). }
    ELSE IF phaseKey = "RELAY_CONSTELLATION" { phaseMapSet(phaseMap, phaseKey, phaseRelayConstellation@). }
    ELSE IF phaseKey = "SCANSAT_OPS" { phaseMapSet(phaseMap, phaseKey, phaseScansatOps@). }
    ELSE IF phaseKey = "LAND_DEORBIT" { phaseMapSet(phaseMap, phaseKey, phaseLandDeorbit@). }
    ELSE IF phaseKey = "LAND" { phaseMapSet(phaseMap, phaseKey, phaseLand@). }
    ELSE IF phaseKey = "LAND_ASSIST" { phaseMapSet(phaseMap, phaseKey, phaseLandAssist@). }
    ELSE IF phaseKey = "ROVER" { phaseMapSet(phaseMap, phaseKey, phaseRover@). }
    ELSE IF phaseKey = "MOLNIYA" { phaseMapSet(phaseMap, phaseKey, phaseMolniya@). }
    ELSE IF phaseKey = "MOLNIYA_INSERT" { phaseMapSet(phaseMap, phaseKey, phaseMolniyaInsert@). }
    ELSE IF phaseKey = "DROP_FOR_IMPACT_AND_RAISE_PE" { phaseMapSet(phaseMap, phaseKey, phaseDropForImpactAndRaisePe@). }
    ELSE IF phaseKey = "DONE" { phaseMapSet(phaseMap, phaseKey, phaseDone@). }
    ELSE IF phaseKey = "SHAPE" { phaseMapSet(phaseMap, phaseKey, phaseShape@). }
    ELSE IF phaseKey = "DEPARTURE_SHAPE" { phaseMapSet(phaseMap, phaseKey, phaseDepartureShape@). }
    ELSE IF phaseKey = "BPLANE" { phaseMapSet(phaseMap, phaseKey, phaseBplane@). }
    ELSE IF phaseKey = "REFINE_BPLANE" { phaseMapSet(phaseMap, phaseKey, phaseRefineBplane@). }
    ELSE IF phaseKey = "GOTO" { phaseMapSet(phaseMap, phaseKey, phaseGoto@). }
    ELSE IF phaseKey = "AIRCLIMB" { phaseMapSet(phaseMap, phaseKey, phaseAirclimb@). }
    ELSE IF phaseKey = "ROCKETCLIMB" { phaseMapSet(phaseMap, phaseKey, phaseRocketclimb@). }
    ELSE IF phaseKey = "SSTO_DEORBIT" { phaseMapSet(phaseMap, phaseKey, phaseSstoDeorbit@). }
    ELSE IF phaseKey = "REENTRY" { phaseMapSet(phaseMap, phaseKey, phaseReentry@). }
    ELSE IF phaseKey = "APPROACH" { phaseMapSet(phaseMap, phaseKey, phaseApproach@). }
    ELSE IF phaseKey = "ARM" { phaseMapSet(phaseMap, phaseKey, phaseArm@). }
    ELSE IF phaseKey = "FLY" { phaseMapSet(phaseMap, phaseKey, phaseFly@). }
}
