// Shared landing config and target helpers.

GLOBAL LAND_CFG_TOUCHDOWN_SPEED IS 2.0.
GLOBAL LAND_CFG_HOVER_ALT IS 100.
GLOBAL LAND_CFG_UPRIGHT_ALT IS 10.
GLOBAL LAND_CFG_BURN_MARGIN IS 1.05.
GLOBAL LAND_CFG_MAX_TILT IS 15.
GLOBAL LAND_CFG_TARGET_LAT IS 0.
GLOBAL LAND_CFG_TARGET_LNG IS 0.
GLOBAL LAND_CFG_TARGET_WAYPOINT IS "".
GLOBAL LAND_CFG_TARGET_LOCK IS FALSE.
GLOBAL LAND_CFG_TARGET_TOLERANCE IS 10000.
GLOBAL LAND_CFG_GUIDANCE_ALT IS 5000.
GLOBAL LAND_CFG_GUIDANCE_CORRECTION_THRESHOLD IS 500.
GLOBAL LAND_CFG_TR_BRAKE_WINDOW IS 250.
GLOBAL LAND_CFG_TR_BRAKE_BIAS IS 0.35.
GLOBAL LAND_CFG_CROSS_PID_KP IS 0.01.
GLOBAL LAND_CFG_CROSS_PID_KI IS 0.001.
GLOBAL LAND_CFG_CROSS_PID_KD IS 0.005.
GLOBAL LAND_CFG_CROSS_PID_MIN IS -15.
GLOBAL LAND_CFG_CROSS_PID_MAX IS 15.
GLOBAL LAND_CFG_TERMINAL_HSPEED IS 15.
GLOBAL LAND_CFG_TERMINAL_ALT IS 1000.
GLOBAL LAND_CFG_BRAKE_ACCEL_FRACTION IS 0.9.
GLOBAL LAND_CFG_BRAKE_MARGIN IS 500.
GLOBAL LAND_CFG_APPROACH_RADIUS IS 750.
GLOBAL LAND_CFG_VERTICAL_RADIUS IS 60.
GLOBAL LAND_CFG_APPROACH_HSPEED IS 25.
GLOBAL LAND_CFG_VERTICAL_HSPEED IS 5.
GLOBAL LAND_CFG_MAX_APPROACH_SPEED IS 35.
GLOBAL LAND_CFG_TERRAIN_CHECK_RADIUS IS 500.
GLOBAL LAND_CFG_TERRAIN_CHECK_STEP IS 100.
GLOBAL LAND_CFG_TERRAIN_VALIDATE IS TRUE.
GLOBAL LAND_CFG_TERRAIN_SAFE_ALT IS 6500.
GLOBAL LAND_CFG_TERRAIN_MIN_CLEARANCE IS 100.
GLOBAL LAND_CFG_TERRAIN_MAX_CRASH_DIST IS 500.
GLOBAL LAND_CFG_TERRAIN_MIN_DESCENT_ANGLE IS 40.

LOCAL FUNCTION _landingCfg {
    PARAMETER key.
    PARAMETER current.
    IF CFG:HASKEY(key) { RETURN CFG[key]. }
    RETURN current.
}

GLOBAL FUNCTION landingApplyMissionConfig {
    IF DEFINED CFG {
        SET LAND_CFG_TOUCHDOWN_SPEED TO _landingCfg("TOUCHDOWN_SPEED", LAND_CFG_TOUCHDOWN_SPEED).
        SET LAND_CFG_HOVER_ALT TO _landingCfg("HOVER_ALT", LAND_CFG_HOVER_ALT).
        SET LAND_CFG_UPRIGHT_ALT TO _landingCfg("UPRIGHT_ALT", LAND_CFG_UPRIGHT_ALT).
        SET LAND_CFG_BURN_MARGIN TO _landingCfg("BURN_MARGIN", LAND_CFG_BURN_MARGIN).
        SET LAND_CFG_MAX_TILT TO _landingCfg("MAX_TILT", LAND_CFG_MAX_TILT).
        SET LAND_CFG_TARGET_LAT TO _landingCfg("TARGET_LAT", LAND_CFG_TARGET_LAT).
        SET LAND_CFG_TARGET_LNG TO _landingCfg("TARGET_LNG", LAND_CFG_TARGET_LNG).
        SET LAND_CFG_TARGET_WAYPOINT TO _landingCfg("TARGET_WAYPOINT", LAND_CFG_TARGET_WAYPOINT).
        SET LAND_CFG_TARGET_LOCK TO _landingCfg("TARGET_LOCK", LAND_CFG_TARGET_LOCK).
        SET LAND_CFG_TARGET_TOLERANCE TO _landingCfg("TARGET_TOLERANCE", LAND_CFG_TARGET_TOLERANCE).
        SET LAND_CFG_GUIDANCE_ALT TO _landingCfg("GUIDANCE_ALT", LAND_CFG_GUIDANCE_ALT).
        SET LAND_CFG_GUIDANCE_CORRECTION_THRESHOLD TO _landingCfg("GUIDANCE_CORRECTION_THRESHOLD", LAND_CFG_GUIDANCE_CORRECTION_THRESHOLD).
        SET LAND_CFG_TR_BRAKE_WINDOW TO _landingCfg("TR_BRAKE_WINDOW", LAND_CFG_TR_BRAKE_WINDOW).
        SET LAND_CFG_TR_BRAKE_BIAS TO _landingCfg("TR_BRAKE_BIAS", LAND_CFG_TR_BRAKE_BIAS).
        SET LAND_CFG_CROSS_PID_KP TO _landingCfg("CROSS_PID_KP", LAND_CFG_CROSS_PID_KP).
        SET LAND_CFG_CROSS_PID_KI TO _landingCfg("CROSS_PID_KI", LAND_CFG_CROSS_PID_KI).
        SET LAND_CFG_CROSS_PID_KD TO _landingCfg("CROSS_PID_KD", LAND_CFG_CROSS_PID_KD).
        SET LAND_CFG_CROSS_PID_MIN TO _landingCfg("CROSS_PID_MIN", LAND_CFG_CROSS_PID_MIN).
        SET LAND_CFG_CROSS_PID_MAX TO _landingCfg("CROSS_PID_MAX", LAND_CFG_CROSS_PID_MAX).
        SET LAND_CFG_TERMINAL_HSPEED TO _landingCfg("TERMINAL_HSPEED", LAND_CFG_TERMINAL_HSPEED).
        SET LAND_CFG_TERMINAL_ALT TO _landingCfg("TERMINAL_ALT", LAND_CFG_TERMINAL_ALT).
        SET LAND_CFG_BRAKE_ACCEL_FRACTION TO _landingCfg("BRAKE_ACCEL_FRACTION", LAND_CFG_BRAKE_ACCEL_FRACTION).
        SET LAND_CFG_BRAKE_MARGIN TO _landingCfg("BRAKE_MARGIN", LAND_CFG_BRAKE_MARGIN).
        SET LAND_CFG_APPROACH_RADIUS TO _landingCfg("APPROACH_RADIUS", LAND_CFG_APPROACH_RADIUS).
        SET LAND_CFG_VERTICAL_RADIUS TO _landingCfg("VERTICAL_RADIUS", LAND_CFG_VERTICAL_RADIUS).
        SET LAND_CFG_APPROACH_HSPEED TO _landingCfg("APPROACH_HSPEED", LAND_CFG_APPROACH_HSPEED).
        SET LAND_CFG_VERTICAL_HSPEED TO _landingCfg("VERTICAL_HSPEED", LAND_CFG_VERTICAL_HSPEED).
        SET LAND_CFG_MAX_APPROACH_SPEED TO _landingCfg("MAX_APPROACH_SPEED", LAND_CFG_MAX_APPROACH_SPEED).
        SET LAND_CFG_TERRAIN_CHECK_RADIUS TO _landingCfg("TERRAIN_CHECK_RADIUS", LAND_CFG_TERRAIN_CHECK_RADIUS).
        SET LAND_CFG_TERRAIN_CHECK_STEP TO _landingCfg("TERRAIN_CHECK_STEP", LAND_CFG_TERRAIN_CHECK_STEP).
        SET LAND_CFG_TERRAIN_VALIDATE TO _landingCfg("TERRAIN_VALIDATE", LAND_CFG_TERRAIN_VALIDATE).
        SET LAND_CFG_TERRAIN_SAFE_ALT TO _landingCfg("TERRAIN_SAFE_ALT", LAND_CFG_TERRAIN_SAFE_ALT).
        SET LAND_CFG_TERRAIN_MIN_CLEARANCE TO _landingCfg("TERRAIN_MIN_CLEARANCE", LAND_CFG_TERRAIN_MIN_CLEARANCE).
        SET LAND_CFG_TERRAIN_MAX_CRASH_DIST TO _landingCfg("TERRAIN_MAX_CRASH_DIST", LAND_CFG_TERRAIN_MAX_CRASH_DIST).
        SET LAND_CFG_TERRAIN_MIN_DESCENT_ANGLE TO _landingCfg("TERRAIN_MIN_DESCENT_ANGLE", LAND_CFG_TERRAIN_MIN_DESCENT_ANGLE).
    }
}

GLOBAL FUNCTION landingResolveTarget {
    LOCAL result IS LEXICON("FOUND", FALSE, "LAT", 0, "LNG", 0, "SOURCE", "none").

    IF LAND_CFG_TARGET_WAYPOINT <> "" {
        LOCAL namedWp IS waypointNamed(LAND_CFG_TARGET_WAYPOINT).
        IF namedWp <> 0 {
            SET result["FOUND"] TO TRUE.
            SET result["LAT"] TO namedWp:GEOPOSITION:LAT.
            SET result["LNG"] TO namedWp:GEOPOSITION:LNG.
            SET result["SOURCE"] TO "waypoint:" + namedWp:NAME.
            RETURN result.
        }
        mLogWarn("Landing waypoint '" + LAND_CFG_TARGET_WAYPOINT
            + "' not found on " + SHIP:BODY:NAME + ".").
    }

    IF LAND_CFG_TARGET_LOCK
            AND (LAND_CFG_TARGET_LAT <> 0 OR LAND_CFG_TARGET_LNG <> 0) {
        SET result["FOUND"] TO TRUE.
        SET result["LAT"] TO LAND_CFG_TARGET_LAT.
        SET result["LNG"] TO LAND_CFG_TARGET_LNG.
        SET result["SOURCE"] TO "locked config".
        RETURN result.
    }

    LOCAL selectedWp IS selectedWaypoint().
    IF selectedWp <> 0 {
        SET result["FOUND"] TO TRUE.
        SET result["LAT"] TO selectedWp:GEOPOSITION:LAT.
        SET result["LNG"] TO selectedWp:GEOPOSITION:LNG.
        SET result["SOURCE"] TO "selected waypoint:" + selectedWp:NAME.
        RETURN result.
    }

    IF LAND_CFG_TARGET_LAT <> 0 OR LAND_CFG_TARGET_LNG <> 0 {
        SET result["FOUND"] TO TRUE.
        SET result["LAT"] TO LAND_CFG_TARGET_LAT.
        SET result["LNG"] TO LAND_CFG_TARGET_LNG.
        SET result["SOURCE"] TO "config".
        RETURN result.
    }

    RETURN result.
}

LOCAL FUNCTION _getImpactDistance {
    LOCAL landingTarget IS landingResolveTarget().
    IF NOT landingTarget["FOUND"] { RETURN 999999. }
    IF NOT ADDONS:TR:AVAILABLE { RETURN 999999. }
    ADDONS:TR:SETTARGET(LATLNG(landingTarget["LAT"], landingTarget["LNG"])).
    WAIT 0.5.
    IF NOT ADDONS:TR:HASIMPACT { RETURN 999999. }
    LOCAL impactPos IS ADDONS:TR:IMPACTPOS.
    RETURN geoDistance(impactPos:LAT, impactPos:LNG,
        landingTarget["LAT"], landingTarget["LNG"]).
}

GLOBAL FUNCTION landingFlyoverPe {
    LOCAL landingTarget IS landingResolveTarget().
    IF NOT landingTarget["FOUND"] { RETURN 12000. }
    RETURN LATLNG(landingTarget["LAT"], landingTarget["LNG"]):TERRAINHEIGHT + 12000.
}

GLOBAL FUNCTION landingFlyoverDistance {
    LOCAL landingTarget IS landingResolveTarget().
    IF NOT landingTarget["FOUND"] { RETURN 999999. }
    LOCAL flyUt IS TIME:SECONDS + ETA:PERIAPSIS.
    LOCAL geo IS SHIP:BODY:GEOPOSITIONOF(POSITIONAT(SHIP, flyUt)).
    RETURN geoDistance(geo:LAT, geo:LNG,
        landingTarget["LAT"], landingTarget["LNG"]).
}

GLOBAL FUNCTION landingImpactWithinTolerance {
    IF SHIP:STATUS = "LANDED" OR SHIP:STATUS = "SPLASHED" { RETURN TRUE. }
    RETURN _getImpactDistance() <= LAND_CFG_TARGET_TOLERANCE.
}

GLOBAL FUNCTION landingImpactAcceptableForAssist {
    IF _getImpactDistance() <= 10000 { RETURN TRUE. }
    IF SHIP:PERIAPSIS > landingFlyoverPe() + 500 { RETURN FALSE. }
    RETURN landingFlyoverDistance() <= 10000.
}
