// --- Config defaults owned by this file ---
GLOBAL TARGET_LAT IS 0.
GLOBAL TARGET_LNG IS 0.
GLOBAL TARGET_LOCK IS 0.
GLOBAL TARGET_WAYPOINT IS "".
GLOBAL LANDING_ASSIST_IMPACT_LIMIT IS 20000.
GLOBAL TOUCHDOWN_SPEED IS 2.
GLOBAL HIGH_DESCENT_SPEED IS 30.
GLOBAL HOVER_ALT IS 100.
GLOBAL UPRIGHT_ALT IS 10.
GLOBAL LANDING_HARD_BRAKE_UP_BIAS IS 0.2.
GLOBAL LANDING_HKILL_THROTTLE_MIN IS 0.15.
GLOBAL LANDING_HKILL_THROTTLE_MAX IS 0.7.
GLOBAL LANDING_FINAL_HOVER_ALT IS 15.
GLOBAL LANDING_FINAL_HOVER_VSPEED IS 0.2.
GLOBAL LANDING_FINAL_HOVER_HSPEED IS 0.3.
GLOBAL LANDING_TARGET_REFINE_HSPEED IS 1.
GLOBAL LANDING_TARGET_REFINE_ACCEPT_TIME IS 10.
GLOBAL LANDING_TARGET_REFINE_ACCEPT_HSPEED IS 5.5.
GLOBAL LANDING_TARGET_REFINE_IMPACT_TOLERANCE IS 500.
GLOBAL LANDING_TARGET_REFINE_RETRO_RESPONSE IS 8.
GLOBAL LANDING_TARGET_REFINE_RETRO_WEIGHT IS 0.45.
GLOBAL LANDING_TARGET_REFINE_IMPACT_SCALE IS 1200.
GLOBAL LANDING_TARGET_REFINE_IMPACT_WEIGHT IS 0.65.
GLOBAL LANDING_TARGET_REFINE_THR_MIN IS 0.2.
GLOBAL LANDING_TARGET_REFINE_THR_MAX IS 0.35.
GLOBAL LANDING_TARGET_REFINE_MAX_TIME IS 20.
GLOBAL LANDING_TARGET_REFINE_CLIMB_LIMIT IS 5.
GLOBAL LANDING_COAST_MCC_TRIGGER_DIST IS 500.
GLOBAL LANDING_COAST_MCC_ACCEPT_DIST IS 250.
GLOBAL LANDING_COAST_MCC_LEAD_DIST IS 3000.
GLOBAL LANDING_COAST_MCC_MIN_BRAKE_ETA IS 60.
GLOBAL LANDING_COAST_MCC_THROTTLE IS 0.05.
GLOBAL LANDING_COAST_MCC_PULSE_TIME IS 0.25.
GLOBAL LANDING_COAST_MCC_SETTLE_TIME IS 2.
GLOBAL LANDING_COAST_MCC_ALIGN_DEG IS 5.
GLOBAL LANDING_COAST_MCC_MAX_UP_DOT IS 0.1.
GLOBAL LANDING_COAST_MCC_CLIMB_LIMIT IS 5.
GLOBAL LANDING_HOVER_REFINE_LEAD_TIME IS 30.
GLOBAL LANDING_HOVER_REFINE_MAX_SPEED IS 4.
GLOBAL LANDING_HOVER_REFINE_SPEED_GAIN IS 0.05.
GLOBAL LANDING_HOVER_REFINE_TARGET_WEIGHT IS 2.5.
GLOBAL LANDING_HOVER_REFINE_ACCEPT_RADIUS IS 30.
GLOBAL LANDING_HOVER_REFINE_ACCEPT_HSPEED IS 1.75.
GLOBAL BURN_MARGIN IS 1.1.
GLOBAL TR_BRAKE_WINDOW IS 250.
GLOBAL TR_BRAKE_BIAS IS 0.35.
GLOBAL CROSS_PID_KP IS 0.01.
GLOBAL CROSS_PID_KI IS 0.001.
GLOBAL CROSS_PID_KD IS 0.005.
GLOBAL CROSS_PID_MIN IS -15.
GLOBAL CROSS_PID_MAX IS 15.
GLOBAL TERMINAL_HSPEED IS 1.
GLOBAL TERMINAL_ALT IS 1000.
GLOBAL BRAKE_ACCEL_FRACTION IS 1.0.
GLOBAL BRAKE_MARGIN IS 500.
GLOBAL APPROACH_RADIUS IS 750.
GLOBAL VERTICAL_RADIUS IS 60.
GLOBAL APPROACH_HSPEED IS 18.
GLOBAL LANDING_LOW_ALT_HSPEED IS 2.
GLOBAL VERTICAL_HSPEED IS 1.
GLOBAL MAX_APPROACH_SPEED IS 55.
GLOBAL APPROACH_SPEED_ALTITUDE_WINDOW IS 3000.
GLOBAL TERRAIN_VALIDATE IS TRUE.
GLOBAL TERRAIN_SAFE_ALT IS 6500.
GLOBAL TERRAIN_MIN_CLEARANCE IS 100.
GLOBAL TERRAIN_MAX_CRASH_DIST IS 500.
GLOBAL TERRAIN_MIN_DESCENT_ANGLE IS 40.
GLOBAL TERRAIN_CHECK_RADIUS IS 100.
GLOBAL TERRAIN_CHECK_STEP IS 20.
GLOBAL MAX_TILT IS 15.
GLOBAL GUIDANCE_ALT IS 5000.
GLOBAL GUIDANCE_CORRECTION_THRESHOLD IS 500.

// Shared landing config and target helpers.

GLOBAL FUNCTION landingApplyMissionConfig {
    // Mission config is already applied directly to the globals above.
    RETURN TRUE.
}

GLOBAL FUNCTION landingResolveTarget {
    LOCAL result IS LEXICON("FOUND", FALSE, "LAT", 0, "LNG", 0, "SOURCE", "none").

    IF TARGET_WAYPOINT <> "" {
        LOCAL namedWp IS waypointNamed(TARGET_WAYPOINT).
        IF namedWp <> 0 {
            SET result["FOUND"] TO TRUE.
            SET result["LAT"] TO namedWp:GEOPOSITION:LAT.
            SET result["LNG"] TO namedWp:GEOPOSITION:LNG.
            SET result["SOURCE"] TO "waypoint:" + namedWp:NAME.
            RETURN result.
        }
        mLogWarn("Landing waypoint '" + TARGET_WAYPOINT
            + "' not found on " + SHIP:BODY:NAME + ".").
    }

    IF TARGET_LOCK
            AND (TARGET_LAT <> 0 OR TARGET_LNG <> 0) {
        SET result["FOUND"] TO TRUE.
        SET result["LAT"] TO TARGET_LAT.
        SET result["LNG"] TO TARGET_LNG.
        SET result["SOURCE"] TO "locked config".
        RETURN result.
    }

    LOCAL selectedWp IS selectedWaypoint().
    IF selectedWp <> 0 {
        SET result["FOUND"] TO TRUE.
        SET result["LAT"] TO selectedWp:GEOPOSITION:LAT.
        SET result["LNG"] TO selectedWp:GEOPOSITION:LNG.
        SET result["SOURCE"] TO "selected waypoint:" + selectedWp:NAME.
        RETURN result.
    }

    IF TARGET_LAT <> 0 OR TARGET_LNG <> 0 {
        SET result["FOUND"] TO TRUE.
        SET result["LAT"] TO TARGET_LAT.
        SET result["LNG"] TO TARGET_LNG.
        SET result["SOURCE"] TO "config".
        RETURN result.
    }

    RETURN result.
}

LOCAL FUNCTION _getImpactDistance {
    LOCAL landingTarget IS landingResolveTarget().
    IF NOT landingTarget["FOUND"] { RETURN 999999. }
    IF NOT ADDONS:TR:AVAILABLE { RETURN 999999. }
    ADDONS:TR:SETTARGET(LATLNG(landingTarget["LAT"], landingTarget["LNG"])).
    WAIT 0.5.
    IF NOT ADDONS:TR:HASIMPACT { RETURN 999999. }
    LOCAL impactPos IS ADDONS:TR:IMPACTPOS.
    RETURN geoDistance(impactPos:LAT, impactPos:LNG,
        landingTarget["LAT"], landingTarget["LNG"]).
}

GLOBAL FUNCTION landingFlyoverPe {
    LOCAL landingTarget IS landingResolveTarget().
    IF NOT landingTarget["FOUND"] { RETURN 0. }
    RETURN LATLNG(landingTarget["LAT"], landingTarget["LNG"]):TERRAINHEIGHT.
}

GLOBAL FUNCTION landingFlyoverDistance {
    LOCAL landingTarget IS landingResolveTarget().
    IF NOT landingTarget["FOUND"] { RETURN 999999. }
    LOCAL flyUt IS TIME:SECONDS + ETA:PERIAPSIS.
    LOCAL geo IS SHIP:BODY:GEOPOSITIONOF(POSITIONAT(SHIP, flyUt)).
    RETURN geoDistance(geo:LAT, geo:LNG,
        landingTarget["LAT"], landingTarget["LNG"]).
}

GLOBAL FUNCTION landingImpactWithinTolerance {
    IF SHIP:STATUS = "LANDED" OR SHIP:STATUS = "SPLASHED" { RETURN TRUE. }
    RETURN _getImpactDistance() <= TARGET_TOLERANCE.
}

GLOBAL FUNCTION landingImpactAcceptableForAssist {
    IF _getImpactDistance() <= LANDING_ASSIST_IMPACT_LIMIT { RETURN TRUE. }
    IF SHIP:PERIAPSIS > landingFlyoverPe() + 500 { RETURN FALSE. }
    RETURN landingFlyoverDistance() <= LANDING_ASSIST_IMPACT_LIMIT.
}
