// KerboScript mission profile.
SET MISSION_ID TO "lko_roundtrip".
SET MISSION_NAME TO "FSS1 LKO Round Trip".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST().
SET SEQUENCE TO LIST("PREFLIGHT", "AIRCLIMB", "ROCKETCLIMB", "SSTO_DEORBIT", "REENTRY", "APPROACH", "DONE").
SET SSTO_TARGET_AP TO 80000.
SET SSTO_REENTRY_PE TO 28000.
SET SSTO_DEORBIT_LEAD_DEG TO 70.
SET SSTO_RUNWAY TO "KSC".
