// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "kerbin_scansat_249",
    "MISSION_NAME", "Kerbin SCANsat 249 km Mapper",
    "TARGET", "KERBIN",
    "PAYLOADS", "SCANSAT",
    "SEQUENCE", "LAUNCH,FAIR,ANTS,PARK,RAISE,CIRC,INCLINE,SCANSAT_OPS,DONE",
    "PARKING_ALT", 85000,
    "LAUNCH_INCLINATION", 90,
    "TARGET_PE", 249000,
    "TARGET_AP", 249000,
    "TARGET_INCLINATION", 90,
    "SCANSAT_POWER_GUARD", 1,
    "SCANSAT_POWER_LOW", 0.3,
    "SCANSAT_POWER_RESUME", 0.6,
    "SCANSAT_DECOUPLER_TAG", "scansat_decoupler",
    "SCANSAT_DISPOSE_CARRIER", 1,
    "SCANSAT_DISPOSE_PE", 30000,
    "SCANSAT_DISPOSE_MAX_TIME", 600,
    "SCANSAT_CLEARANCE_DV", 2,
    "SCANSAT_CLEARANCE_DIR", "NORMAL",
    "SCANSAT_CLEARANCE_THROTTLE", 0.25,
    "SCANSAT_CLEARANCE_SETTLE", 3
).
