// KerboScript mission profile.
SET MISSION_ID TO "krbcap1_lko".
SET MISSION_NAME TO "KRBCAP1 LKO Orbit".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("KRBCAP1").
SET SEQUENCE TO LIST("LAUNCH", "ANTS", "PARK", "KSC_DEORBIT", "DESCENT", "DONE").
SET PARKING_ALT TO 74000.
SET LAUNCH_INCLINATION TO 30.
SET LIBS_EXTRA TO LIST("descent").
SET ORBIT_STAY_TIME TO 10800.
SET TARGET_LAT TO -0.1.
SET TARGET_LNG TO -74.25.
SET TARGET_TOLERANCE TO 15000.
SET REENTRY_PE TO 30000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 6.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 128.
SET TARGET_DEORBIT_MIN_LEAD TO 300.
SET DESCENT_RELEASE_ALT TO 38000.
