// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "krbcap1_polar_tour",
    "MISSION_NAME", "KRBCAP1 Polar Biome Tour",
    "TARGET", "KERBIN",
    "PAYLOADS", "KRBCAP1",
    "SEQUENCE", "LAUNCH,ANTS,PARK,KSC_DEORBIT,DESCENT,DONE",
    "PARKING_ALT", 74000,
    "LAUNCH_INCLINATION", 80,
    "LIBS_EXTRA", "descent",
    "ORBIT_STAY_TIME", 216000,
    "TARGET_LAT", 72.94,
    "TARGET_LNG", -82.97,
    "TARGET_TOLERANCE", 2000,
    "EVA_BIOMES", "tundra, ice, cold",
    "REENTRY_PE", 30000,
    "TARGET_DEORBIT_SCAN_ORBITS", 28,
    "TARGET_DEORBIT_SCAN_SAMPLES", 896,
    "TARGET_DEORBIT_MIN_LEAD", 300,
    "DESCENT_RELEASE_ALT", 38000
).
