// KerboScript mission profile.
SET MISSION_ID TO "krbcap1_suborbital_ksc".
SET MISSION_NAME TO "KRBCAP1 Round-the-World Hop".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO "KRBCAP1".
SET SEQUENCE TO "LAUNCH,SUBORBIT,DESCENT,DONE".
SET PARKING_ALT TO 85000.
SET LAUNCH_INCLINATION TO 0.
SET SUBORBIT_RETURN TO 1.
SET SUBORBIT_RETURN_TOL TO 40000.
SET LIBS_EXTRA TO "suborbit@SUBORBIT, descent".
SET DESCENT_DECOUPLER_TAG TO "descent_decoupler".
SET DESCENT_DECOUPLE_ALT TO -100.
SET DESCENT_RELEASE_ALT TO 38000.
