// KerboScript mission profile.
SET MISSION_ID TO "krbcap1_polar_tour".
SET MISSION_NAME TO "KRBCAP1 Polar Biome Tour".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST("KRBCAP1").
SET SEQUENCE TO LIST("LAUNCH", "ANTS", "PARK", "KSC_DEORBIT", "DESCENT", "DONE").
SET PARKING_ALT TO 74000.
SET LAUNCH_INCLINATION TO 80.
SET LIBS_EXTRA TO LIST("descent").
SET ORBIT_STAY_TIME TO 216000.
SET TARGET_LAT TO 72.94.
SET TARGET_LNG TO -82.97.
SET TARGET_TOLERANCE TO 2000.
SET EVA_BIOMES TO "tundra, ice, cold".
SET REENTRY_PE TO 30000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 28.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 896.
SET TARGET_DEORBIT_MIN_LEAD TO 300.
SET DESCENT_RELEASE_ALT TO 38000.
