// KerboScript mission profile.
SET MISSION_CFG TO LEXICON(
    "MISSION_ID", "minmus_crew_orbit",
    "MISSION_NAME", "Minmus Crewed Science Orbit",
    "TARGET", "MINMUS",
    "PAYLOADS", "CREW",
    "SEQUENCE", "PRELAUNCH,LAUNCH,FAIR,ANTS,PARK,XING,BPLANE,COAST_1HALF,REFINE_BPLANE,COAST_2HALF,CAPTURE,SHAPE,RELAY_OPS,DONE",
    "PARKING_ALT", 85000,
    "LAUNCH_INCLINATION", 0,
    "CAPTURE_PE", 15000,
    "CAPTURE_INC", 90,
    "CAPTURE_DIR", "POLAR",
    "TARGET_PE", 30000,
    "TARGET_AP", 30000,
    "SHAPE_PE", 30000,
    "SHAPE_AP", 30000,
    "SHAPE_INC", 90,
    "REENTRY_PE", 43000,
    "KEEP_WARP", 1
).
