// KerboScript mission profile.
SET MISSION_ID TO "rescue_lko".
SET MISSION_NAME TO "LKO Rescue".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO "KRBCAP1".
SET SEQUENCE TO "PRELAUNCH,LAUNCH,ANTS,PARK,RDV,MATCH,CREW_XFER,KSC_DEORBIT,DESCENT,DONE".
SET PARKING_ALT TO 73500.
SET LIBS_EXTRA TO "launch@PARK, descent".
SET TARGET_LAT TO -0.1.
SET TARGET_LNG TO -74.25.
SET TARGET_TOLERANCE TO 15000.
SET REENTRY_PE TO 30000.
SET TARGET_DEORBIT_SCAN_ORBITS TO 4.
SET TARGET_DEORBIT_SCAN_SAMPLES TO 128.
SET TARGET_DEORBIT_MIN_LEAD TO 90.
SET DESCENT_DECOUPLER_TAG TO "descent_decoupler".
SET DESCENT_DECOUPLE_ALT TO 45000.
