SET MISSION_ID TO "ka201_island_to_ksc_turn".
SET MISSION_NAME TO "FBIJ KA201 Island to KSC Turn".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST().
SET SEQUENCE TO LIST("PREFLIGHT", "FLIGHT", "POSTFLIGHT", "DONE").
