// KerboScript mission profile.
SET MISSION_ID TO "touch_and_go".
SET MISSION_NAME TO "FBIJ Touch And Go Practice".
SET TARGET_ TO "KERBIN".
SET PAYLOADS TO LIST().
SET SEQUENCE TO LIST("PREFLIGHT", "FLIGHT", "POSTFLIGHT", "DONE").
